export const GET_CHARACTERS = "GET_CHARACTERS";
export const ADD_TO_CART_CHARACTERS = "ADD_TO_CART_CHARACTERS";
export const GET_EPISODES = "GET_EPISODES";
export const ADD_TO_CART_EPISODES = "ADD_TO_CART_EPISODES";
export const REMOVE_ONE_FROM_CART = "REMOVE_ONE_FROM_CART";
export const REMOVE_ALL_FROM_CART = "REMOVE_ALL_FROM_CART";
export const CLEAR_CART = "CLEAR_CART";