export const GET_CHARACTERS = "GET_CHARACTERS";
export const GET_EPISODES = "GET_EPISODES";
export const ADD_TO_CART_CHARACTERS = "ADD_TO_CART_CHARACTERS";
export const ADD_TO_CART_EPISODES = "ADD_TO_CART_EPISODES";
export const REMOVE_FROM_CART_CHARACTERS = "REMOVE_FROM_CART_CHARACTERS";
export const REMOVE_FROM_CART_EPISODES = "REMOVE_FROM_CART_EPISODES";
